# Register user
POST http://{{host}}:{{port}}/auth/v1/accounts
Content-Type: application/json

{
  "username": "user",
  "password": "password",
  "email": "t@test.com"
}

###

# Register user
POST http://{{host}}:{{port}}/v1/users
Content-Type: application/json

{
  "username": "user2",
  "password": "password",
  "email": "t2@test.com"
}

###

# Login
POST http://{{host}}:{{port}}/v1/sessions
Content-Type: application/json

{
  "username": "user",
  "password": "password"
}
###

# Create a post
POST http://{{host}}:{{port}}/v1/posts
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "body": "a post body"
}

###

# Get user profile
GET http://{{host}}:{{port}}/v1/users/user
Authorization: Bearer {{token}}
Accept: application/json

###

# Edit profile
PATCH http://{{host}}:{{port}}/v1/users
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "username": "user3",
  "bio": "Bios"
}

###

# Follow user
POST http://{{host}}:{{port}}/v1/users/user2/followers
Authorization: Bearer {{token}}
Accept: application/json

###

# Unfollow user
DELETE http://{{host}}:{{port}}/v1/users/user2/followers
Authorization: Bearer {{token}}
Accept: application/json

###

# Get user's friends (following)
GET http://{{host}}:{{port}}/v1/users/user/friends
Authorization: Bearer {{token}}
Accept: application/json

###

# Get user's followers (following)
GET http://{{host}}:{{port}}/v1/users/user/followers
Authorization: Bearer {{token}}
Accept: application/json

###
