POST http://{{host}}:{{port}}/v1/users/new
Content-Type: application/json

{
  "username": "user",
  "password": "password",
  "email": "t@test.com"
}

###

POST http://{{host}}:{{port}}/v1/users/new
Content-Type: application/json

{
  "username": "user2",
  "password": "password",
  "email": "t2@test.com"
}

###

POST http://{{host}}:{{port}}/v1/auth/login
Content-Type: application/json

{
  "username": "user",
  "password": "password"
}
###

POST http://{{host}}:{{port}}/v1/posts
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "body": "a post body"
}

###

GET http://{{host}}:{{port}}/v1/users/user
Authorization: Bearer {{token}}
Accept: application/json

###

PATCH http://{{host}}:{{port}}/v1/users
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "username": "user3",
  "bio": "Bios"
}

###

PUT http://{{host}}:{{port}}/v1/users/use/followers
Authorization: Bearer {{token}}
Accept: application/json

###
